### ISSUE TITLE
Limitation of 260 Character for url

### ISSUE THREAD

**Issue by ayan84** [csharp-leaf/Leaf.xNet#109]
Strange problem, when I try to post a url which have more than 260 character long queries, the following error occurred,

**The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.**

`
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Leaf.xNet.FileContent..ctor(String pathToContent, Int32 bufferSize)
   at Leaf.xNet.HttpRequest.Post(String address, String path)
   at Test.Form21.btnXnet_Click(Object sender, EventArgs e) in F:\Soft\REverse\Test\Test\Test\Form21.cs:line 925`

you can create this scenario by creating any request over 260 character long. What is the workaround now?

**Comment by DeclanFrampton** [comment]
I am not able to replicate the issue, can you provide a URL you are trying to perform a post request on?
