### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by D1og0** [csharp-leaf/Leaf.xNet#128]
Hello, I'm getting a proxy issue, whatever proxy I try to use.

Here is my code (http://hastebin.com/irisedobup.csharp) 

and my issue is 

Leaf.xNet.HttpException: Unable to connect to the HTTP-server 'gw.api.animedigitalnetwork.fr'. ---> Leaf.xNet.ProxyException: Received invalid status code 'BadRequest' on '182.23.211.108:80' proxy.
   at Leaf.xNet.HttpProxyClient.CreateConnection(String destinationHost, Int32 destinationPort, TcpClient tcpClient)
   at Leaf.xNet.HttpRequest.CreateTcpConnection(String host, Int32 port)
   --- End of inner exception stack trace ---
   at Leaf.xNet.HttpRequest.CreateTcpConnection(String host, Int32 port)
   at Leaf.xNet.HttpRequest.CreateConnection(Uri address)
   at Leaf.xNet.HttpRequest.TryCreateConnectionOrUseExisting(Uri address, Uri previousAddress)
   at Leaf.xNet.HttpRequest.Request(HttpMethod method, Uri address, HttpContent content)
   at Leaf.xNet.HttpRequest.Raw(HttpMethod method, Uri address, HttpContent content)
   at Leaf.xNet.HttpRequest.Raw(HttpMethod method, String address, HttpContent content)
   at Leaf.xNet.HttpRequest.Post(String address, String str, String contentType)
   at All_In_One.Checker.ADN.Run(List`1 comboList, List`1 proxies) in C:\Users\diogo\Desktop\All-In-One\All-In-One\Checker\ADN.cs:line 39

**Comment by Plot1337** [comment]
Can you connect to that proxy server normally?

**Comment by Plot1337** [comment]
UPDATE: Please consider switching to .NET 6 and use the built-in HttpClient. I made a library to simplify the proxy usage process: https://github.com/Plot1337/EzNetProxy
